package domain.auth.exception

class NotFoundUserException : RuntimeException()
